// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAViKsW9Cp739-5zhf8j4rjR1BsDeT3-34',
    appId: '1:452740244497:web:82dd71c7428b4bcee77db0',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    authDomain: 'sanchari-app-a2d2d.firebaseapp.com',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    measurementId: 'G-96FL91MY3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4eTBiqiQemvUW3TS7X1n7NNpO_10n7ag',
    appId: '1:452740244497:android:9f64b9ab58ffe551e77db0',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdcDV8HuW7ILqrwaclxTV9P-T6kz4QU70',
    appId: '1:452740244497:ios:87aaae35479ca7c3e77db0',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    iosBundleId: 'com.example.sanchariApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdcDV8HuW7ILqrwaclxTV9P-T6kz4QU70',
    appId: '1:452740244497:ios:87aaae35479ca7c3e77db0',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    iosBundleId: 'com.example.sanchariApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAViKsW9Cp739-5zhf8j4rjR1BsDeT3-34',
    appId: '1:452740244497:web:a51acbd59726b225e77db0',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    authDomain: 'sanchari-app-a2d2d.firebaseapp.com',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    measurementId: 'G-GJJ425PN14',
  );
}
