// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'place_your_api',
    appId: 'your_api_ID',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    authDomain: 'sanchari-app-a2d2d.firebaseapp.com',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    measurementId: 'G-96FL91MY3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'place_your_api',
    appId: 'apiid',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'apiKEY',
    appId: 'apiID',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    iosBundleId: 'com.example.sanchariApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: 'API_ID',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    iosBundleId: 'com.example.sanchariApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: 'API_ID',
    messagingSenderId: '452740244497',
    projectId: 'sanchari-app-a2d2d',
    authDomain: 'sanchari-app-a2d2d.firebaseapp.com',
    storageBucket: 'sanchari-app-a2d2d.firebasestorage.app',
    measurementId: 'G-GJJ425PN14',
  );
}
